/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class VCliente extends javax.swing.JFrame {

    private MCliente cliente = null;
    private MServidor servidor = null;
    int mousepX;
    int mousepY;

    /**
     * Creates new form VistaCliente
     */
    public VCliente() {
        initComponents();
    }

    public VCliente(MServidor servidor) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.servidor = servidor;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlExit = new javax.swing.JLabel();
        jlMinimizar = new javax.swing.JLabel();
        jtfNick = new javax.swing.JTextField();
        jlConectar = new javax.swing.JLabel();
        jlDesconectar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlLista = new javax.swing.JList<>();
        jtfChat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 59, 134));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PECCORINA");

        jlExit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlExit.setForeground(new java.awt.Color(255, 255, 255));
        jlExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit.setText("X");
        jlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlExitMouseExited(evt);
            }
        });

        jlMinimizar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setText("_");
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseExited(evt);
            }
        });

        jtfNick.setText("Nick");

        jlConectar.setBackground(new java.awt.Color(72, 59, 134));
        jlConectar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlConectar.setForeground(new java.awt.Color(255, 255, 255));
        jlConectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlConectar.setText("CONECTAR");
        jlConectar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlConectar.setOpaque(true);
        jlConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlConectarMouseExited(evt);
            }
        });

        jlDesconectar.setBackground(new java.awt.Color(72, 59, 134));
        jlDesconectar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        jlDesconectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDesconectar.setText("DESCONECTAR");
        jlDesconectar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlDesconectar.setOpaque(true);
        jlDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDesconectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlDesconectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlDesconectarMouseExited(evt);
            }
        });

        jtaChat.setBackground(new java.awt.Color(67, 114, 146));
        jtaChat.setColumns(20);
        jtaChat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtaChat.setForeground(new java.awt.Color(255, 255, 255));
        jtaChat.setLineWrap(true);
        jtaChat.setRows(5);
        jScrollPane1.setViewportView(jtaChat);

        jlLista.setBackground(new java.awt.Color(67, 114, 146));
        jlLista.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlLista.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jlLista);

        jtfChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfChatKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfChat)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfNick, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlDesconectar)))
                        .addGap(348, 348, 348))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jtfNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlExit)
                        .addComponent(jlMinimizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfChat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel dlm = new DefaultListModel();
    private void jlConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConectarMouseClicked
        // TODO add your handling code here:
        jlLista.setModel(dlm);
        try {
            int puerto = servidor.getPort();

            String nick = jtfNick.getText();
            if (cliente == null) {
                cliente = new MCliente(puerto, "127.0.0.1", nick, this);
                cliente.start();
            }
            jlConectar.setEnabled(false);
            jlDesconectar.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la entrada de datos");
            cliente = null;
        }
    }//GEN-LAST:event_jlConectarMouseClicked

    private void jlConectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConectarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlConectar.setBackground(Color.WHITE);
        jlConectar.setForeground(color);
    }//GEN-LAST:event_jlConectarMouseEntered

    private void jlConectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConectarMouseExited
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlConectar.setBackground(color);
        jlConectar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlConectarMouseExited

    private void jlDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDesconectarMouseClicked
        // TODO add your handling code here:
        if (cliente != null) {
            cliente.enviarTrama(3, "");
            cliente.interrupt();
            servidor.interrupt();
            this.dispose();
        }
        cliente = null;
        jlConectar.setEnabled(true);
        jlDesconectar.setEnabled(false);
        dlm.removeAllElements();
        jtaChat.setText("");
        servidor.interrupt();
        this.dispose();
    }//GEN-LAST:event_jlDesconectarMouseClicked

    private void jlDesconectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDesconectarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlDesconectar.setBackground(Color.WHITE);
        jlDesconectar.setForeground(color);
    }//GEN-LAST:event_jlDesconectarMouseEntered

    private void jlDesconectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDesconectarMouseExited
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlDesconectar.setBackground(color);
        jlDesconectar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlDesconectarMouseExited

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jlMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(11, 227, 243);
        jlMinimizar.setForeground(color);
    }//GEN-LAST:event_jlMinimizarMouseEntered

    private void jlMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseExited
        // TODO add your handling code here:
        jlMinimizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMinimizarMouseExited

    private void jlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jlExitMouseClicked

    private void jlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseEntered
        // TODO add your handling code here:
        Color color = new Color(11, 227, 243);
        jlExit.setForeground(color);
    }//GEN-LAST:event_jlExitMouseEntered

    private void jlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseExited
        // TODO add your handling code here:
        jlExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlExitMouseExited

    private void jtfChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfChatKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cliente.enviarMensaje(jtfChat.getText());
            jtfChat.setText("");
        }
    }//GEN-LAST:event_jtfChatKeyPressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();

        this.setLocation(coordX - mousepX, coordY - mousepY);
    }//GEN-LAST:event_jPanel1MouseDragged

    public void mensajeRecibido(String sMensaje) {
        jtaChat.append(sMensaje + "\n");
    }

    public void nuevaPersona(String nick) {
        dlm.addElement(nick);
    }

    public void borrarPersona(int nPos) {
        dlm.remove(nPos);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlConectar;
    private javax.swing.JLabel jlDesconectar;
    private javax.swing.JLabel jlExit;
    private javax.swing.JList<String> jlLista;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JTextArea jtaChat;
    private javax.swing.JTextField jtfChat;
    private javax.swing.JTextField jtfNick;
    // End of variables declaration//GEN-END:variables
}
