/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Disenno;

import Tablas.AdminTableModel;
import Tablas.TablaMensajeModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import peccorina.Cliente;
import peccorina.SistemaPeccorina;
import peccorina.Usuario;

/**
 *
 * @author alumno
 */
public class VistaAdmin extends javax.swing.JFrame {

    Usuario u;
    private ArrayList<Cliente> lista;
    private SistemaPeccorina sistema;
    private AdminTableModel etm;
    private TablaMensajeModel tmm;
    private int mousepX;
    private int mousepY;

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin(Usuario user) {
        this.u = user;
        cargarJframe();
        verTabla();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }

    public VistaAdmin() {
        cargarJframe();
        verTabla();
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called& from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedor = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jlExit = new javax.swing.JLabel();
        jlMinimizar = new javax.swing.JLabel();
        jlBorrar = new javax.swing.JLabel();
        jlAviso = new javax.swing.JLabel();
        jlMensaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMensaje = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtMensajes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscarTodo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpContenedor.setBackground(new java.awt.Color(72, 59, 134));
        jpContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jpContenedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpContenedorMouseDragged(evt);
            }
        });
        jpContenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpContenedorMousePressed(evt);
            }
        });

        jtUsuarios.setModel(etm);
        jScrollPane2.setViewportView(jtUsuarios);

        jlExit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlExit.setForeground(new java.awt.Color(255, 255, 255));
        jlExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit.setText("X");
        jlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlExitMouseExited(evt);
            }
        });

        jlMinimizar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setText("_");
        jlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseExited(evt);
            }
        });

        jlBorrar.setBackground(new java.awt.Color(72, 59, 134));
        jlBorrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jlBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBorrar.setText("BORRAR USUARIO");
        jlBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBorrar.setOpaque(true);
        jlBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBorrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBorrarMouseExited(evt);
            }
        });

        jlAviso.setBackground(new java.awt.Color(72, 59, 134));
        jlAviso.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlAviso.setForeground(new java.awt.Color(255, 255, 255));
        jlAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAviso.setText("ENVIAR AVISO");
        jlAviso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlAviso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlAviso.setOpaque(true);
        jlAviso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAvisoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAvisoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAvisoMouseExited(evt);
            }
        });

        jlMensaje.setBackground(new java.awt.Color(72, 59, 134));
        jlMensaje.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jlMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMensaje.setText("ENVIAR MENSAJE");
        jlMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlMensaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMensaje.setOpaque(true);
        jlMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMensajeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMensajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMensajeMouseExited(evt);
            }
        });

        jtaMensaje.setColumns(20);
        jtaMensaje.setLineWrap(true);
        jtaMensaje.setRows(5);
        jScrollPane1.setViewportView(jtaMensaje);

        jtMensajes.setModel(tmm);
        jScrollPane3.setViewportView(jtMensajes);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUSCAR:");

        buscarTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarTodoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContenedorLayout.createSequentialGroup()
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpContenedorLayout.createSequentialGroup()
                                .addComponent(jlMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpContenedorLayout.createSequentialGroup()
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpContenedorLayout.createSequentialGroup()
                                .addComponent(jlBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContenedorLayout.createSequentialGroup()
                                .addComponent(jlMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorLayout.createSequentialGroup()
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlExit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpContenedorLayout.createSequentialGroup()
                        .addGroup(jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBorrarMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarMensajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBorrarMensajesActionPerformed

    private void jbBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarUsuarioActionPerformed

    }//GEN-LAST:event_jbBorrarUsuarioActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jButtonCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCDActionPerformed

    }//GEN-LAST:event_jButtonCDActionPerformed

    private void jpContenedorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpContenedorMouseDragged
        // TODO add your handling code here:
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();

        this.setLocation(coordX - mousepX, coordY - mousepY);
    }//GEN-LAST:event_jpContenedorMouseDragged

    private void jpContenedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpContenedorMousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jpContenedorMousePressed

    private void jlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jlExitMouseClicked

    private void jlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseEntered
        // TODO add your handling code here:
        Color color = new Color(11, 227, 243);
        jlExit.setForeground(color);
    }//GEN-LAST:event_jlExitMouseEntered

    private void jlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseExited
        // TODO add your handling code here:
        jlExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlExitMouseExited

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jlMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(11, 227, 243);
        jlMinimizar.setForeground(color);
    }//GEN-LAST:event_jlMinimizarMouseEntered

    private void jlMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseExited
        // TODO add your handling code here:
        jlMinimizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMinimizarMouseExited

    private void jlBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBorrarMouseClicked
        // TODO add your handling code here:
        int seleccion;
        if (jtUsuarios.getSelectedRow() > 0) {
            seleccion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar el usuario?", "Peccorina", JOptionPane.YES_NO_OPTION);
            if (seleccion == JOptionPane.OK_OPTION) {
                sistema.eliminarUsuario(lista.get(jtUsuarios.getSelectedRow()));
                JOptionPane.showMessageDialog(this, "Usuario eliminado con éxito");
                actualizarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla");
        }
    }//GEN-LAST:event_jlBorrarMouseClicked

    private void jlBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBorrarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlBorrar.setBackground(Color.WHITE);
        jlBorrar.setForeground(color);
    }//GEN-LAST:event_jlBorrarMouseEntered

    private void jlBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBorrarMouseExited
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlBorrar.setBackground(color);
        jlBorrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlBorrarMouseExited

    private void jlAvisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAvisoMouseClicked
        // TODO add your handling code here:
        String aviso = "Cumpla las normas.";
        if (jtUsuarios.getSelectedRow() > 0) {
            sistema.enviarMensaje(u.getCorreoUsuario(), aviso, lista.get(jtUsuarios.getSelectedRow()).getCorreoUsuario());
            JOptionPane.showMessageDialog(this, "Mensaje enviado con éxito");
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla");
        }
    }//GEN-LAST:event_jlAvisoMouseClicked

    private void jlAvisoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAvisoMouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlAviso.setBackground(Color.WHITE);
        jlAviso.setForeground(color);
    }//GEN-LAST:event_jlAvisoMouseEntered

    private void jlAvisoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAvisoMouseExited
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlAviso.setBackground(color);
        jlAviso.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlAvisoMouseExited

    private void jlMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMensajeMouseClicked
        // TODO add your handling code here:
        if (jtUsuarios.getSelectedRow() > 0) {
            sistema.enviarMensaje(u.getCorreoUsuario(), jtaMensaje.getText(), lista.get(jtUsuarios.getSelectedRow()).getCorreoUsuario());
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla");
        }
    }//GEN-LAST:event_jlMensajeMouseClicked

    private void jlMensajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMensajeMouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlMensaje.setBackground(Color.WHITE);
        jlMensaje.setForeground(color);
    }//GEN-LAST:event_jlMensajeMouseEntered

    private void jlMensajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMensajeMouseExited
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlMensaje.setBackground(color);
        jlMensaje.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMensajeMouseExited

    private void buscarTodoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTodoKeyReleased

        String buscar = buscarTodo.getText();
        buscarV(buscar);


    }//GEN-LAST:event_buscarTodoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlAviso;
    private javax.swing.JLabel jlBorrar;
    private javax.swing.JLabel jlExit;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JTable jtMensajes;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JTextArea jtaMensaje;
    // End of variables declaration//GEN-END:variables

    private void cargarJframe() {
        sistema = new SistemaPeccorina();
        lista = sistema.VerClientes();

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VistaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verTabla() {
        etm = new AdminTableModel(sistema.VerClientes());
        tmm = new TablaMensajeModel(sistema.VerMensajes(u));
    }

    private void actualizarTabla() {
        etm = new AdminTableModel(sistema.VerClientes());
        tmm = new TablaMensajeModel(sistema.VerMensajes(u));
        jtUsuarios.setModel(etm);
        jtMensajes.setModel(tmm);
    }

    public void buscarV(String buscar) {

        etm = new AdminTableModel(sistema.buscarClientes(buscar));
        jtUsuarios.setModel(etm);

    }

}
