/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Disenno;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import peccorina.Cliente;
import peccorina.SistemaPeccorina;

/**
 *
 * @author alumno
 */
public class VistaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistro
     */
    //ATRIBUTOS DEL JFRAME
    CardLayout cardLayout;
    File archivo;
    SistemaPeccorina sistema;
    String url;
    int mousepX;
    int mousepY;

    //ATRIBUTOS CREACIÓN DE USUARIO
    Cliente c;
    String sexo, orientacion;
    FileInputStream fis;

    public VistaRegistro() {
        try {
            initComponents();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            this.setLocationRelativeTo(null);
            this.setTitle("Peccorina");
            cardLayout = (CardLayout) (jpContenedor.getLayout());
            sistema = new SistemaPeccorina();
            jlPass.setVisible(false);

        } catch (Exception ex) {
            Logger.getLogger(VistaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedor = new javax.swing.JPanel();
        jpDatos = new javax.swing.JPanel();
        jpSiguiente = new javax.swing.JPanel();
        jbSiguiente = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfCorreo = new javax.swing.JTextField();
        jpfContrasenna = new javax.swing.JPasswordField();
        jpfRepetirCon = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlPass = new javax.swing.JLabel();
        jbExit = new javax.swing.JLabel();
        jlMinimizar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlCancelar = new javax.swing.JLabel();
        jpSexo = new javax.swing.JPanel();
        jpMujer = new javax.swing.JPanel();
        jlMujer = new javax.swing.JLabel();
        jpHombre = new javax.swing.JPanel();
        jlHombre = new javax.swing.JLabel();
        jpAtras = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbExit1 = new javax.swing.JLabel();
        jlMinimizar1 = new javax.swing.JLabel();
        jpOrientacion = new javax.swing.JPanel();
        jpHetero = new javax.swing.JPanel();
        jlHetero = new javax.swing.JLabel();
        jpHomo = new javax.swing.JPanel();
        jlHomo = new javax.swing.JLabel();
        jpBi = new javax.swing.JPanel();
        jlBi = new javax.swing.JLabel();
        jpAtras1 = new javax.swing.JPanel();
        jlAtras1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlExit2 = new javax.swing.JLabel();
        jlMinimizar2 = new javax.swing.JLabel();
        jpFinal = new javax.swing.JPanel();
        jpImagenUser = new javax.swing.JPanel();
        jlImagenUser = new javax.swing.JLabel();
        jpFinalizar = new javax.swing.JPanel();
        jlFinalizar = new javax.swing.JLabel();
        jpAtras2 = new javax.swing.JPanel();
        jlAtras2 = new javax.swing.JLabel();
        jtfEdad = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jcbCiudad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlExit3 = new javax.swing.JLabel();
        jlMinimizar3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jpContenedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpContenedorMouseDragged(evt);
            }
        });
        jpContenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpContenedorMousePressed(evt);
            }
        });
        jpContenedor.setLayout(new java.awt.CardLayout());

        jpDatos.setBackground(new java.awt.Color(67, 114, 146));

        jpSiguiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpSiguiente.setOpaque(false);
        jpSiguiente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSiguiente.setBackground(new java.awt.Color(67, 114, 146));
        jbSiguiente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jbSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbSiguiente.setText("SIGUIENTE");
        jbSiguiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSiguiente.setOpaque(true);
        jbSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbSiguienteMouseExited(evt);
            }
        });
        jpSiguiente.add(jbSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jpfContrasenna.setPreferredSize(new java.awt.Dimension(119, 24));

        jpfRepetirCon.setPreferredSize(new java.awt.Dimension(119, 24));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de usuario:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo electrónico:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Repetir contraseña:");

        jlPass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlPass.setForeground(new java.awt.Color(255, 255, 255));
        jlPass.setText("* Las contraseñas no coinciden");

        jbExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbExit.setForeground(new java.awt.Color(255, 255, 255));
        jbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbExit.setText("X");
        jbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbExitMouseExited(evt);
            }
        });

        jlMinimizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setText("_");
        jlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseExited(evt);
            }
        });

        jlCancelar.setBackground(new java.awt.Color(67, 114, 146));
        jlCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jlCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCancelar.setText("CANCELAR");
        jlCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancelar.setOpaque(true);
        jlCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlPass)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpfContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpfRepetirCon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExit)
                    .addComponent(jlMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpfContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpfRepetirCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        jpContenedor.add(jpDatos, "card2");

        jpSexo.setBackground(new java.awt.Color(67, 114, 146));
        jpSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpSexo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jpSexo.setEnabled(false);

        jpMujer.setBackground(new java.awt.Color(255, 204, 255));
        jpMujer.setOpaque(false);

        jlMujer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMujer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMujerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMujerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMujerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpMujerLayout = new javax.swing.GroupLayout(jpMujer);
        jpMujer.setLayout(jpMujerLayout);
        jpMujerLayout.setHorizontalGroup(
            jpMujerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMujer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpMujerLayout.setVerticalGroup(
            jpMujerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMujer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jlMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mujer.png")));

        jpHombre.setBackground(new java.awt.Color(102, 255, 255));
        jpHombre.setOpaque(false);
        jpHombre.setPreferredSize(new java.awt.Dimension(150, 239));

        jlHombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlHombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHombreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlHombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlHombreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpHombreLayout = new javax.swing.GroupLayout(jpHombre);
        jpHombre.setLayout(jpHombreLayout);
        jpHombreLayout.setHorizontalGroup(
            jpHombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpHombreLayout.setVerticalGroup(
            jpHombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        jlHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombre.png")));

        jpAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpAtras.setOpaque(false);
        jpAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(67, 114, 146));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ATRÁS");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jpAtras.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Indíca tu género");

        jbExit1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbExit1.setForeground(new java.awt.Color(255, 255, 255));
        jbExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbExit1.setText("X");
        jbExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbExit1MouseExited(evt);
            }
        });

        jlMinimizar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlMinimizar1.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar1.setText("_");
        jlMinimizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpSexoLayout = new javax.swing.GroupLayout(jpSexo);
        jpSexo.setLayout(jpSexoLayout);
        jpSexoLayout.setHorizontalGroup(
            jpSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSexoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(80, 80, 80)
                .addComponent(jlMinimizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpSexoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jpMujer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpHombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSexoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jpAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(362, 362, 362))
        );
        jpSexoLayout.setVerticalGroup(
            jpSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSexoLayout.createSequentialGroup()
                .addGroup(jpSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpSexoLayout.createSequentialGroup()
                        .addGroup(jpSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbExit1)
                            .addComponent(jlMinimizar1)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(jpSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpHombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpMujer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)))
                .addGap(24, 24, 24))
        );

        jpContenedor.add(jpSexo, "card3");

        jpOrientacion.setBackground(new java.awt.Color(67, 114, 146));

        jpHetero.setBackground(new java.awt.Color(204, 255, 255));
        jpHetero.setOpaque(false);

        jlHetero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hetero.png"))); // NOI18N
        jlHetero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlHetero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHeteroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlHeteroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlHeteroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpHeteroLayout = new javax.swing.GroupLayout(jpHetero);
        jpHetero.setLayout(jpHeteroLayout);
        jpHeteroLayout.setHorizontalGroup(
            jpHeteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeteroLayout.createSequentialGroup()
                .addComponent(jlHetero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpHeteroLayout.setVerticalGroup(
            jpHeteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHetero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpHomo.setBackground(new java.awt.Color(255, 204, 255));
        jpHomo.setOpaque(false);

        jlHomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/homo.png"))); // NOI18N
        jlHomo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlHomo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHomoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlHomoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlHomoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpHomoLayout = new javax.swing.GroupLayout(jpHomo);
        jpHomo.setLayout(jpHomoLayout);
        jpHomoLayout.setHorizontalGroup(
            jpHomoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHomo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpHomoLayout.setVerticalGroup(
            jpHomoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlHomo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpBi.setBackground(new java.awt.Color(204, 0, 204));
        jpBi.setOpaque(false);

        jlBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bi.png"))); // NOI18N
        jlBi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpBiLayout = new javax.swing.GroupLayout(jpBi);
        jpBi.setLayout(jpBiLayout);
        jpBiLayout.setHorizontalGroup(
            jpBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBiLayout.setVerticalGroup(
            jpBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpAtras1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpAtras1.setOpaque(false);
        jpAtras1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlAtras1.setBackground(new java.awt.Color(67, 114, 146));
        jlAtras1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlAtras1.setForeground(new java.awt.Color(255, 255, 255));
        jlAtras1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAtras1.setText("ATRÁS");
        jlAtras1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlAtras1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlAtras1.setOpaque(true);
        jlAtras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAtras1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAtras1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAtras1MouseExited(evt);
            }
        });
        jpAtras1.add(jlAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selecciona tu preferencia sexual");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Heterosexual");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Homosexual");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bisexual");

        jlExit2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlExit2.setForeground(new java.awt.Color(255, 255, 255));
        jlExit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit2.setText("X");
        jlExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlExit2MouseExited(evt);
            }
        });

        jlMinimizar2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlMinimizar2.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar2.setText("_");
        jlMinimizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpOrientacionLayout = new javax.swing.GroupLayout(jpOrientacion);
        jpOrientacion.setLayout(jpOrientacionLayout);
        jpOrientacionLayout.setHorizontalGroup(
            jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrientacionLayout.createSequentialGroup()
                .addGroup(jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOrientacionLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlMinimizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpOrientacionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOrientacionLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jpHomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpHetero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jpBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpOrientacionLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOrientacionLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jpAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpOrientacionLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel8)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel9)))))
                .addGap(10, 10, 10))
        );
        jpOrientacionLayout.setVerticalGroup(
            jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrientacionLayout.createSequentialGroup()
                .addGroup(jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlExit2)
                        .addComponent(jlMinimizar2)))
                .addGap(78, 78, 78)
                .addGroup(jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHomo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHetero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jpOrientacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addComponent(jpAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jpContenedor.add(jpOrientacion, "card4");

        jpFinal.setBackground(new java.awt.Color(67, 114, 146));
        jpFinal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpImagenUser.setBackground(new java.awt.Color(255, 255, 255));
        jpImagenUser.setOpaque(false);
        jpImagenUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlImagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jlImagenUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlImagenUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlImagenUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlImagenUserMouseClicked(evt);
            }
        });
        jpImagenUser.add(jlImagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        jpFinal.add(jpImagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jpFinalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpFinalizar.setOpaque(false);

        jlFinalizar.setBackground(new java.awt.Color(67, 114, 146));
        jlFinalizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        jlFinalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFinalizar.setText("FINALIZAR");
        jlFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlFinalizar.setOpaque(true);
        jlFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlFinalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlFinalizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpFinalizarLayout = new javax.swing.GroupLayout(jpFinalizar);
        jpFinalizar.setLayout(jpFinalizarLayout);
        jpFinalizarLayout.setHorizontalGroup(
            jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFinalizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpFinalizarLayout.setVerticalGroup(
            jpFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFinalizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpFinal.add(jpFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jpAtras2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpAtras2.setOpaque(false);

        jlAtras2.setBackground(new java.awt.Color(67, 114, 146));
        jlAtras2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlAtras2.setForeground(new java.awt.Color(255, 255, 255));
        jlAtras2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAtras2.setText("ATRÁS");
        jlAtras2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlAtras2.setOpaque(true);
        jlAtras2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAtras2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlAtras2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAtras2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpAtras2Layout = new javax.swing.GroupLayout(jpAtras2);
        jpAtras2.setLayout(jpAtras2Layout);
        jpAtras2Layout.setHorizontalGroup(
            jpAtras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAtras2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlAtras2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpAtras2Layout.setVerticalGroup(
            jpAtras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAtras2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlAtras2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpFinal.add(jpAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));
        jpFinal.add(jtfEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 119, 130, -1));
        jpFinal.add(jtfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 161, 130, -1));

        jcbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Álava", "Albacete", "Badajoz", "Barcelona", "Cáceres", "Cádiz", "Gerona", "Granada", "Huelva", "Huesca", "La Coruña", "La Rioja", "Madrid", "Málaga", "Palencia", "Potenvedra", "Salamanca", "Segovia", "Tarragona", "Teruel", "Valencia", "Valladolid", "Zamora", "Zaragoza" }));
        jcbCiudad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCiudadActionPerformed(evt);
            }
        });
        jpFinal.add(jcbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 207, 130, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edad:");
        jpFinal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 123, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ciudad:");
        jpFinal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Teléfono:");
        jpFinal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 165, -1, -1));

        jlExit3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlExit3.setForeground(new java.awt.Color(255, 255, 255));
        jlExit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit3.setText("X");
        jlExit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlExit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlExit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlExit3MouseExited(evt);
            }
        });
        jpFinal.add(jlExit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 5, 40, -1));

        jlMinimizar3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlMinimizar3.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimizar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar3.setText("_");
        jlMinimizar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMinimizar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMinimizar3MouseExited(evt);
            }
        });
        jpFinal.add(jlMinimizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 5, 40, -1));

        jpContenedor.add(jpFinal, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbExitMouseClicked

    private void jbSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSiguienteMouseClicked
        // TODO add your handling code here:
        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(jtfCorreo.getText());

        if (jtfNombre.getText().isEmpty() || jtfCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo vacío");
        } else {
            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(this, "Inserte un correo válido");
            } else {
                if (jpfContrasenna.getPassword().length != 0 && Arrays.equals(jpfContrasenna.getPassword(), jpfRepetirCon.getPassword())) {
                    cardLayout.next(jpContenedor);
                } else {
                    jlPass.setVisible(true);
                }
            }

        }
    }//GEN-LAST:event_jbSiguienteMouseClicked

    private void jbExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbExit1MouseClicked

    private void jlHombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHombreMouseEntered
        // TODO add your handling code here:
        jlHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombreHover.png")));
    }//GEN-LAST:event_jlHombreMouseEntered

    private void jlHombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHombreMouseExited
        // TODO add your handling code here:
        jlHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombre.png")));
    }//GEN-LAST:event_jlHombreMouseExited

    private void jlMujerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMujerMouseEntered
        // TODO add your handling code here:
        jlMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mujerHover.png")));
    }//GEN-LAST:event_jlMujerMouseEntered

    private void jlMujerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMujerMouseExited
        // TODO add your handling code here:
        jlMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mujer.png")));
    }//GEN-LAST:event_jlMujerMouseExited

    private void jlHombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHombreMouseClicked
        // TODO add your handling code here:
        this.sexo = "hombre";
        cardLayout.next(jpContenedor);
    }//GEN-LAST:event_jlHombreMouseClicked

    private void jlMujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMujerMouseClicked
        // TODO add your handling code here:
        this.sexo = "mujer";
        cardLayout.next(jpContenedor);
    }//GEN-LAST:event_jlMujerMouseClicked

    private void jlExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExit2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jlExit2MouseClicked

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jlMinimizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizar2MouseClicked

    private void jlMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar1MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizar1MouseClicked

    private void jlHeteroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHeteroMouseClicked
        // TODO add your handling code here:
        this.orientacion = "heterosexual";
        cardLayout.next(jpContenedor);
    }//GEN-LAST:event_jlHeteroMouseClicked

    private void jlHomoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHomoMouseClicked
        // TODO add your handling code here:
        this.orientacion = "homosexual";
        cardLayout.next(jpContenedor);
    }//GEN-LAST:event_jlHomoMouseClicked

    private void jlBiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBiMouseClicked
        // TODO add your handling code here:
        this.orientacion = "bisexual";
        cardLayout.next(jpContenedor);
    }//GEN-LAST:event_jlBiMouseClicked

    private void jlMinimizar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar3MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizar3MouseClicked

    private void jlExit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExit3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jlExit3MouseClicked

    private void jlAtras1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAtras1MouseClicked
        // TODO add your handling code here:
        cardLayout.previous(jpContenedor);
    }//GEN-LAST:event_jlAtras1MouseClicked

    private void jlFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFinalizarMouseClicked
        // TODO add your handling code here:
        if (jtfTelefono.getText().isEmpty() || jtfEdad.getText().isEmpty() || jcbCiudad.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Campo vacío");

        } else {

            if (Integer.parseInt(jtfEdad.getText()) < 18) {

                JOptionPane.showMessageDialog(this, "Prohibido para menores de 18");

                this.dispose();

            } else {

                if (url == null) {

                    JOptionPane.showMessageDialog(this, "Imagen requerida");

                } else {
                    JOptionPane.showMessageDialog(this, "Registro completado");
                    //CREAR CLIENTE
                    int darLike = 0;
                    int recibirLike = 0;
                   
                    c = new Cliente(sexo, Integer.parseInt(jtfEdad.getText()), orientacion, jcbCiudad.getSelectedItem().toString(), jtfTelefono.getText(),
                            fis, darLike, recibirLike, jtfNombre.getText(), jtfCorreo.getText(), Arrays.toString(jpfContrasenna.getPassword()), "cliente");

                    sistema.crearUsuario(c);
                    sistema.crearCliente(c, url);
                    VistaInicio vi = new VistaInicio();

                    vi.setVisible(true);

                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jlFinalizarMouseClicked

    private void jlAtras2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAtras2MouseClicked
        // TODO add your handling code here:
        cardLayout.previous(jpContenedor);
    }//GEN-LAST:event_jlAtras2MouseClicked

    private void jlFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFinalizarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(27, 91, 93);
        jlFinalizar.setBackground(color);
    }//GEN-LAST:event_jlFinalizarMouseEntered

    private void jlFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFinalizarMouseExited
        // TODO add your handling code here:
        Color color = new Color(67, 114, 146);
        jlFinalizar.setBackground(color);
    }//GEN-LAST:event_jlFinalizarMouseExited

    private void jlAtras2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAtras2MouseEntered
        // TODO add your handling code here:
        Color color = new Color(27, 91, 93);
        jlAtras2.setBackground(color);
    }//GEN-LAST:event_jlAtras2MouseEntered

    private void jlAtras2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAtras2MouseExited
        // TODO add your handling code here:
        Color color = new Color(67, 114, 146);
        jlAtras2.setBackground(color);
    }//GEN-LAST:event_jlAtras2MouseExited

    private void jbSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSiguienteMouseEntered
        // TODO add your handling code here:
        Color color = new Color(27, 91, 93);
        jbSiguiente.setBackground(color);
    }//GEN-LAST:event_jbSiguienteMouseEntered

    private void jbSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSiguienteMouseExited
        // TODO add your handling code here:
        Color color = new Color(67, 114, 146);
        jbSiguiente.setBackground(color);
    }//GEN-LAST:event_jbSiguienteMouseExited

    private void jlAtras1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAtras1MouseEntered
        // TODO add your handling code here:
        Color color = new Color(27, 91, 93);
        jlAtras1.setBackground(color);
    }//GEN-LAST:event_jlAtras1MouseEntered

    private void jlAtras1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAtras1MouseExited
        // TODO add your handling code here:
        Color color = new Color(67, 114, 146);
        jlAtras1.setBackground(color);
    }//GEN-LAST:event_jlAtras1MouseExited

    private void jpContenedorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpContenedorMouseDragged
        // TODO add your handling code here:
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();

        this.setLocation(coordX - mousepX, coordY - mousepY);
    }//GEN-LAST:event_jpContenedorMouseDragged

    private void jpContenedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpContenedorMousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jpContenedorMousePressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        cardLayout.previous(jpContenedor);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        Color color = new Color(27, 91, 93);
        jLabel13.setBackground(color);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        Color color = new Color(67, 114, 146);
        jLabel13.setBackground(color);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jlHeteroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHeteroMouseEntered
        // TODO add your handling code here:
        jlHetero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/heteroHover.png")));
    }//GEN-LAST:event_jlHeteroMouseEntered

    private void jlHeteroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHeteroMouseExited
        // TODO add your handling code here:
        jlHetero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hetero.png")));
    }//GEN-LAST:event_jlHeteroMouseExited

    private void jlHomoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHomoMouseEntered
        // TODO add your handling code here:
        jlHomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/homoHover.png")));
    }//GEN-LAST:event_jlHomoMouseEntered

    private void jlHomoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHomoMouseExited
        // TODO add your handling code here:
        jlHomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/homo.png")));
    }//GEN-LAST:event_jlHomoMouseExited

    private void jlBiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBiMouseEntered
        // TODO add your handling code here:
        jlBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/biHover.png")));
    }//GEN-LAST:event_jlBiMouseEntered

    private void jlBiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBiMouseExited
        // TODO add your handling code here:
        jlBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bi.png")));
    }//GEN-LAST:event_jlBiMouseExited

    private void jlMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlMinimizar.setForeground(color);
    }//GEN-LAST:event_jlMinimizarMouseEntered

    private void jlMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseExited
        // TODO add your handling code here:
        jlMinimizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMinimizarMouseExited

    private void jbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jbExit.setForeground(color);
    }//GEN-LAST:event_jbExitMouseEntered

    private void jbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseExited
        // TODO add your handling code here:
        jbExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbExitMouseExited

    private void jlMinimizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar1MouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlMinimizar1.setForeground(color);
    }//GEN-LAST:event_jlMinimizar1MouseEntered

    private void jlMinimizar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar1MouseExited
        // TODO add your handling code here:
        jlMinimizar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMinimizar1MouseExited

    private void jbExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExit1MouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jbExit1.setForeground(color);
    }//GEN-LAST:event_jbExit1MouseEntered

    private void jbExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExit1MouseExited
        // TODO add your handling code here:
        jbExit1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbExit1MouseExited

    private void jlMinimizar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar2MouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlMinimizar2.setForeground(color);
    }//GEN-LAST:event_jlMinimizar2MouseEntered

    private void jlMinimizar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar2MouseExited
        // TODO add your handling code here:
        jlMinimizar2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMinimizar2MouseExited

    private void jlExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExit2MouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlExit2.setForeground(color);
    }//GEN-LAST:event_jlExit2MouseEntered

    private void jlExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExit2MouseExited
        // TODO add your handling code here:
        jlExit2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlExit2MouseExited

    private void jlMinimizar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar3MouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlMinimizar3.setForeground(color);
    }//GEN-LAST:event_jlMinimizar3MouseEntered

    private void jlMinimizar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizar3MouseExited
        // TODO add your handling code here:
        jlMinimizar3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlMinimizar3MouseExited

    private void jlExit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExit3MouseEntered
        // TODO add your handling code here:
        Color color = new Color(72, 59, 134);
        jlExit3.setForeground(color);
    }//GEN-LAST:event_jlExit3MouseEntered

    private void jlExit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExit3MouseExited
        // TODO add your handling code here:
        jlExit3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlExit3MouseExited

    private void jlImagenUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImagenUserMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int resultado;

            VistaChooser vc = new VistaChooser(this, true);

            FileNameExtensionFilter formato = new FileNameExtensionFilter("JPG, PNG y GIF", "jpg", "png", "gif");

            vc.jfcImg.setFileFilter(formato);

            resultado = vc.jfcImg.showOpenDialog(null);

            if (JFileChooser.APPROVE_OPTION == resultado) {

                archivo = VistaChooser.jfcImg.getSelectedFile();

                url = archivo.getAbsolutePath();

                archivo = new File(url);

                ImageIcon imgIcon = new ImageIcon(archivo.toString());

                Icon icono = new ImageIcon(imgIcon.getImage().getScaledInstance(jlImagenUser.getWidth(), jlImagenUser.getHeight(), Image.SCALE_DEFAULT));

                jlImagenUser.setIcon(icono);

                fis = new FileInputStream(archivo);
            }

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jlImagenUserMouseClicked

    private void jcbCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCiudadActionPerformed

    private void jlCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancelarMouseClicked
        // TODO add your handling code here:
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlCancelarMouseClicked

    private void jlCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancelarMouseEntered
        // TODO add your handling code here:
        Color color = new Color(27, 91, 93);
        jlCancelar.setBackground(color);
    }//GEN-LAST:event_jlCancelarMouseEntered

    private void jlCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancelarMouseExited
        // TODO add your handling code here:
        Color color = new Color(67, 114, 146);
        jlCancelar.setBackground(color);
    }//GEN-LAST:event_jlCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbExit;
    private javax.swing.JLabel jbExit1;
    private javax.swing.JLabel jbSiguiente;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JLabel jlAtras1;
    private javax.swing.JLabel jlAtras2;
    private javax.swing.JLabel jlBi;
    private javax.swing.JLabel jlCancelar;
    private javax.swing.JLabel jlExit2;
    private javax.swing.JLabel jlExit3;
    private javax.swing.JLabel jlFinalizar;
    private javax.swing.JLabel jlHetero;
    private javax.swing.JLabel jlHombre;
    private javax.swing.JLabel jlHomo;
    private javax.swing.JLabel jlImagenUser;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JLabel jlMinimizar1;
    private javax.swing.JLabel jlMinimizar2;
    private javax.swing.JLabel jlMinimizar3;
    private javax.swing.JLabel jlMujer;
    private javax.swing.JLabel jlPass;
    private javax.swing.JPanel jpAtras;
    private javax.swing.JPanel jpAtras1;
    private javax.swing.JPanel jpAtras2;
    private javax.swing.JPanel jpBi;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpFinal;
    private javax.swing.JPanel jpFinalizar;
    private javax.swing.JPanel jpHetero;
    private javax.swing.JPanel jpHombre;
    private javax.swing.JPanel jpHomo;
    private javax.swing.JPanel jpImagenUser;
    private javax.swing.JPanel jpMujer;
    private javax.swing.JPanel jpOrientacion;
    private javax.swing.JPanel jpSexo;
    private javax.swing.JPanel jpSiguiente;
    private javax.swing.JPasswordField jpfContrasenna;
    private javax.swing.JPasswordField jpfRepetirCon;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfEdad;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
